swagger: '2.0'
info:
  description: >
    This is the RESTful API for a user to manage his/her TOTP QR URLs/secrets in
    WSO2 Identity Server. Going forward this will be the API for user portal as
    well as external parties.
  version: v1
  title: WSO2 Identity Server - TOTP API Definition
  contact:
    name: WSO2
    url: 'http://wso2.com/products/identity-server/'
    email: architecture@wso2.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
schemes:
  - https
security:
  - OAuth2: [ ]
  - BasicAuth: [ ]
tags:
  - name: me
    description: Operations for the authenticated user.
consumes:
  - application/json
produces:
  - application/json
paths:
  /server/typingdnaConfig:
    get:
      tags:
        - server
      summary: Retrieve whether typingdna authentication enabled by admin
      description: |
        This API is used to retrieve whether the typingdna authentication enabled by admin or not.
        <b>Permission required:</b>
            * none
        <b>Scope required:</b>
            * internal_login
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/TypingdnaEnableResponse'
        401:
          description: Unauthorized
        403:
          description: Resource Forbidden
        500:
          description: Server Error
          schema:
            $ref: '#/definitions/Error'
  /me/typingpatterns:
    delete:
      tags:
        - me
      summary: Resets TOTP credentials of the authenticated user.
      description: >
        This API is used to delete the TOTP credentials of the authenticated
        user. <b>Permission required:</b><br> * none<br> <b>Scope
        required:</b><br> * internal_login
      responses:
        '200':
          description: Credentials deleted successfully
          schema:
            $ref: '#/definitions/TypingdnaResponse'
        '401':
          description: Unauthorized
        '403':
          description: Resource Forbidden
        '500':
          description: Server Error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Error:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: string
        example: some_error_code
      message:
        type: string
        example: Some Error Message
      description:
        type: string
        example: Some Error Description
      traceId:
        type: string
        example: Some Correlation for Error Instance
  UserRequest:
    type: object
    required:
      - action
    properties:
      action:
        type: string
        example: 'DELETE'
        enum:
          - DELETE
      verificationCode:
        type: integer
        example: Verification code that need to be verified by the server
  TypingdnaResponse:
    type: object
    properties:
      Success:
        type: boolean
        description: Whether typingpatterns deleted successfully or not
      Enabled:
        type: boolean
        description: Whether typingpatterns
  TypingdnaEnableResponse:
    type: object
    properties:
      Enabled:
        type: boolean
        description: Whether typingdna authentication enabled or not

securityDefinitions:
  BasicAuth:
    type: basic
  OAuth2:
    type: oauth2
    flow: accessCode
    authorizationUrl: https://localhost:9443/oauth2/authorize
    tokenUrl: https://localhost:9443/oauth2/token

host: localhost:9443
basePath: /api/typingdna/v1.0
